//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<int> UyrukID { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> Sehir { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Aciklama { get; set; }
        public string EgitimDurumu { get; set; }
        public Nullable<System.DateTime> EgitimBasTarih { get; set; }
        public Nullable<System.DateTime> EgitimBitTarih { get; set; }
        public string DevamDurumu { get; set; }
        public Nullable<int> LiseAdi { get; set; }
        public Nullable<int> UniversiteAdi { get; set; }
        public string OzGecmisDosyaAd { get; set; }
        public string BasvuruSonucu { get; set; }
    
        public virtual Lise Lise { get; set; }
        public virtual Sehir Sehir1 { get; set; }
        public virtual Ulke Ulke { get; set; }
        public virtual Universite Universite { get; set; }
    }
}
